server:
  port: 8081

spring:
  application:
    name: todo-application
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    database-platform: postgresql
    open-in-view: true
    show-sql: true
    format-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics





